#Requires AutoHotkey v2.0

#Include <stdlib\base64>

payload := Buffer(3, 0)
StrPut("abc", payload, "UTF-8")
encoded := stdlib.base64.b64encode(payload)
decoded := stdlib.base64.b64decode("YWJj")
standardEncoded := stdlib.base64.standard_b64encode(payload)
wrappedEncoded := stdlib.base64.encodebytes(payload)
wrappedDecoded := stdlib.base64.decodebytes(wrappedEncoded)
urlsafePayload := Buffer(2, 0)
NumPut("UChar", 0xfb, urlsafePayload, 0)
NumPut("UChar", 0xff, urlsafePayload, 1)
urlsafeEncoded := stdlib.base64.urlsafe_b64encode(urlsafePayload)
urlsafeDecoded := stdlib.base64.urlsafe_b64decode("-_8=")
binaryPayload := Buffer(5, 0)
NumPut("UChar", 0x41, binaryPayload, 0)
NumPut("UChar", 0x42, binaryPayload, 1)
NumPut("UChar", 0x43, binaryPayload, 2)
NumPut("UChar", 0x00, binaryPayload, 3)
NumPut("UChar", 0xff, binaryPayload, 4)
base16Encoded := stdlib.base64.b16encode(binaryPayload)
base16Decoded := stdlib.base64.b16decode("41424300ff", true)

MsgBox "encoded=" StrGet(encoded, "UTF-8")
    . "`ndecoded=" StrGet(decoded, "UTF-8")
    . "`nstandard=" StrGet(standardEncoded, "UTF-8")
    . "`nwrapped=" StrReplace(StrGet(wrappedEncoded, "UTF-8"), "`n", "\n")
    . "`nwrapped decoded=" StrGet(wrappedDecoded, "UTF-8")
    . "`nurlsafe=" StrGet(urlsafeEncoded, "UTF-8")
    . "`nurlsafe bytes=" Format("{:02x}{:02x}", NumGet(urlsafeDecoded, 0, "UChar"), NumGet(urlsafeDecoded, 1, "UChar"))
    . "`nbase16=" StrGet(base16Encoded, "UTF-8")
    . "`nbase16 bytes=" Format("{:02x}{:02x}{:02x}{:02x}{:02x}"
        , NumGet(base16Decoded, 0, "UChar")
        , NumGet(base16Decoded, 1, "UChar")
        , NumGet(base16Decoded, 2, "UChar")
        , NumGet(base16Decoded, 3, "UChar")
        , NumGet(base16Decoded, 4, "UChar"))
