#Requires AutoHotkey v2.0

#Include <stdlib\base64>

payload := Buffer(3, 0)
StrPut("abc", payload, "UTF-8")
encoded := stdlib.base64.b64encode(payload)
decoded := stdlib.base64.b64decode("YWJj")
standardEncoded := stdlib.base64.standard_b64encode(payload)
wrappedEncoded := stdlib.base64.encodebytes(payload)
wrappedDecoded := stdlib.base64.decodebytes(wrappedEncoded)
urlsafePayload := Buffer(2, 0)
NumPut("UChar", 0xfb, urlsafePayload, 0)
NumPut("UChar", 0xff, urlsafePayload, 1)
urlsafeEncoded := stdlib.base64.urlsafe_b64encode(urlsafePayload)
urlsafeDecoded := stdlib.base64.urlsafe_b64decode("-_8=")
binaryPayload := Buffer(5, 0)
NumPut("UChar", 0x41, binaryPayload, 0)
NumPut("UChar", 0x42, binaryPayload, 1)
NumPut("UChar", 0x43, binaryPayload, 2)
NumPut("UChar", 0x00, binaryPayload, 3)
NumPut("UChar", 0xff, binaryPayload, 4)
base16Encoded := stdlib.base64.b16encode(binaryPayload)
base16Decoded := stdlib.base64.b16decode("41424300ff", true)
base32Encoded := stdlib.base64.b32encode(payload)
base32Decoded := stdlib.base64.b32decode("MFRGG===")
base32LowerDecoded := stdlib.base64.b32decode("mfrgg===", true)
base32hexEncoded := stdlib.base64.b32hexencode(payload)
base32hexDecoded := stdlib.base64.b32hexdecode("C5H66===")
base85Encoded := stdlib.base64.b85encode(payload)
base85Decoded := stdlib.base64.b85decode("VPaz")
ascii85Encoded := stdlib.base64.a85encode(payload)
ascii85Decoded := stdlib.base64.a85decode("@:E^")
ascii85Adobe := stdlib.base64.a85encode(payload, { adobe: true })
ascii85Spaces := stdlib.base64.a85encode(StdlibBase64ExampleBytes("    "), { foldspaces: true })

base64_example_output := "encoded=" StrGet(encoded, "UTF-8")
    . "`ndecoded=" StrGet(decoded, "UTF-8")
    . "`nstandard=" StrGet(standardEncoded, "UTF-8")
    . "`nwrapped=" StrReplace(StrGet(wrappedEncoded, "UTF-8"), "`n", "\n")
    . "`nwrapped decoded=" StrGet(wrappedDecoded, "UTF-8")
    . "`nurlsafe=" StrGet(urlsafeEncoded, "UTF-8")
    . "`nurlsafe bytes=" Format("{:02x}{:02x}", NumGet(urlsafeDecoded, 0, "UChar"), NumGet(urlsafeDecoded, 1, "UChar"))
    . "`nbase16=" StrGet(base16Encoded, "UTF-8")
    . "`nbase16 bytes=" Format("{:02x}{:02x}{:02x}{:02x}{:02x}"
        , NumGet(base16Decoded, 0, "UChar")
        , NumGet(base16Decoded, 1, "UChar")
        , NumGet(base16Decoded, 2, "UChar")
        , NumGet(base16Decoded, 3, "UChar")
        , NumGet(base16Decoded, 4, "UChar"))
    . "`nbase32=" StrGet(base32Encoded, "UTF-8")
    . "`nbase32 decoded=" StrGet(base32Decoded, "UTF-8")
    . "`nbase32 lower decoded=" StrGet(base32LowerDecoded, "UTF-8")
    . "`nbase32hex=" StrGet(base32hexEncoded, "UTF-8")
    . "`nbase32hex decoded=" StrGet(base32hexDecoded, "UTF-8")
    . "`nbase85=" StrGet(base85Encoded, "UTF-8")
    . "`nbase85 decoded=" StrGet(base85Decoded, "UTF-8")
    . "`nascii85=" StrGet(ascii85Encoded, "UTF-8")
    . "`nascii85 decoded=" StrGet(ascii85Decoded, "UTF-8")
    . "`nascii85 adobe=" StrGet(ascii85Adobe, "UTF-8")
    . "`nascii85 spaces=" StrGet(ascii85Spaces, "UTF-8")
FileAppend base64_example_output "`n", "*", "UTF-8"

StdlibBase64ExampleBytes(text)
{
    bytes := Buffer(StrPut(text, "UTF-8") - 1, 0)
    if bytes.Size > 0
        StrPut(text, bytes, "UTF-8")
    return bytes
}
